[package]
name = "telly"
authors = ["Dagan Martinez"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.1.0"
num-derive = "0.3.3"
num-traits = "0.2.14"
thiserror = "1.0.30"
